language: node_js
node_js:
  - "6"
addons:
  sonarqube: true
env:
  global:
    - secure: AIFQfucAs3qK6GPOMshpPzzkJhHJgITYhfGKzUmPRIMBABWWeRuiS7oNH0AZ3WgwOdt8cujsY1+sKCW8yIukXAIKFOuyCfBzPjiTDzM+Il1mPuP9nhXEzsQewVGi1O+iAWX1MFBZpudCYY6lzlIVQquchQqYzYIckFD+lKXX1+xlkkucs11szC9l8g3hlP0uHjRjlVey0dKvjQaUi8BuJDS6fbr/c5prOSZnuIcsFOVorO1vNKQmnuGrl8ilK+Kih06LsHZgYofYHEbePhn/Vz1RDyaQAUeb4acGwyMtGS8dMKf1npsy6EVw3WylVLmdIjc+COEZl7otpsPCgtDxZCHxBzdS8l52LnhwfDohJ7nbrIje+f0kzMAgk4rBnhuJQyvy6KgZ3wRfdcCRRX5ZSix8OKgmqfLbCQ3ets78EuzEuu5N1ke6NoPL+a3OK5wxPk9xVrTNdkXdbPoRSj4X/GBTDn98x6Xeb5v4WHr3k3y4hBH3ybnxx/U51VTDpYYwAfE5sWl9GO4Farx8pnXK0NtoO9B+X4f1vDaOCUs5y0dSpHXj5ZNd9O6uet52qAbXYEVLpH6r0wbsTAafy7LXKSQI4IivXhwunLMwlnuW3jz50MhwmlGtDAuZfWbIVqdDi4Mz8h3DNw8w/3/A1Vh46VE5uJ+/hefg+d30QNhXQVw=
    # defines SONAR_TOKEN=abcdef0123456789
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

